In [2]:
import numpy as np

# Displacement gradient: 
dudX = np.matrix([[4,-1,0],[1,-4,2],[4,0,6]]) * 1e-3

# small strain and spin tensor: \epsilon = 1/2 (dudX + dudX^T)
eps = 0.5 * ( dudX + np.transpose(dudX))
# spin tensor: \epsilon = 1/2 (dudX - dudX^T)
omega = 0.5 * ( dudX - np.transpose(dudX))
print 'eps=',eps
print 'omg=',omega

# volumetric strain and deviatoric strain
e = eps.trace()
dev_strain = eps - (e[0,0]/3)*np.identity(3)
print 'e=',e
print 'dev_strain=',dev_strain

# Invariants
I1 = eps.trace()
I2 = 0.5*(eps.trace()**2-(eps*eps).trace())
I3 = np.linalg.det(eps)
print 'I1=',I1[0,0],' I2=',I2[0,0],' I3=',I3

# Eigenvalues and vectors.
w,v = np.linalg.eig(eps)
print 'Eigenvalues=',w
print 'Eigenvectors=', v

eps= [[ 0.004  0.     0.002]
 [ 0.    -0.004  0.001]
 [ 0.002  0.001  0.006]]
omg= [[ 0.    -0.001 -0.002]
 [ 0.001  0.     0.001]
 [ 0.002 -0.001  0.   ]]
e= [[ 0.006]]
dev_strain= [[ 0.002  0.     0.002]
 [ 0.    -0.006  0.001]
 [ 0.002  0.001  0.004]]
I1= 0.006  I2= -2.1e-05  I3= -8.4e-08
Eigenvalues= [ 0.00730045  0.0028036  -0.00410405]
Eigenvectors= [[ 0.51677237  0.855742   -0.02553306]
 [ 0.07546517 -0.07523995 -0.99430577]
 [ 0.85279031 -0.51190289  0.10346065]]
